# Generated by Django 4.1.1 on 2022-09-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz", name="slug", field=models.SlugField(blank=True),
        ),
    ]
